### ISSUE TITLE
Replace anyhow dependency

### ISSUE THREAD

**Issue by cking** [Finomnis/tokio-graceful-shutdown#13]
In my project I am not using `anyhow` and dont plan to - `snafu` implements something similar with `Whatever` if needed.

The problem is: I would love to use this project, but I have to use this dependency just for the callbacks.

IMO it would be nicer and easier to use a boxed error (`Box<Error + Send + Sync>`) - this introduces no extra dependency on anyhow and at the same time can contain all errors thrown at it.

**Comment by Finomnis** [comment]
I use anyhow for everything I do, so I wasn't aware that this might be an issue. Thanks for bringing it up.

I was under the impression that anyhow::Result IS just an alias of Result<.., Box<Error + Send + Sync>>. So the fact that I use it should be transparent to the code using this crate. Am I incorrect with this assumption?

So is the reason you bring this up because you don't want to use anyhow yourself, or because you think this crate is more heavy-weight than it should be?

**Comment by Finomnis** [comment]
Something like this?

**Comment by cking** [comment]
> So is the reason you bring this up because you don't want to use anyhow yourself
That would be right. This library isn't heavy weight at all.

> I was under the impression that anyhow::Result IS just an alias of Result<.., Box<Error + Send + Sync>>
I can neither confirm or deny it, but when I throw my error with no anyhow in my dependencies, it complains that I'm not throwing the correct type

> Something like this?
It is 4 am right now for me, I'll try it later today. It doesn't look bad at first glance. If it doesn't work I'll provide a minimal reproducible example.

**Comment by cking** [comment]
yes it works.

**Comment by Finomnis** [comment]
Sadly, I'll have to release it as 0.5.0, because it is a breaking change in some corner cases.
I'll do so later today, when I have time.

**Comment by TheButlah** [comment]
https://docs.rs/tokio-graceful-shutdown/latest/tokio_graceful_shutdown/struct.Toplevel.html#method.start
The current published version still uses `anyhow`. I have the same problem as OP. Personally I use `eyre::Result` instead of `anyhow::Result`. But everyone using this package is going to want their own error type, so it makes sense to have it be either the box dyn error version, or have it parameterized on the error type.

Is there any reason it needs to be a box dyn error instead of parameterized on the error type as a generic? You can always have the generic default to the boxed dyn.

**Comment by Finomnis** [comment]
Reopened until v0.6 is released.

@TheButlah Yes, this already got fixed in main, I'll release a beta soon.
I'd appreciate your feedback then :)

I'll add an eyre example.

**Comment by Finomnis** [comment]
Released as `v0.6.0-beta.0`.

Feedback appreciated, I want to make sure that the existing API is satisfactory for everyone before releasing the stable v0.6.0.

**Comment by Finomnis** [comment]
@TheButlah I thought about parameterizing it on your own error type, but that would have had to be done *everywhere*, including the Handle that you receive in every function. Further, you would loose the ability to mix & match return types of different subsystems.

I'm still thinking about it, but I feel like the generic approach of Box<dyn Error> is more suitable to this usecase.

**Comment by TheButlah** [comment]
why not make the default for the parameter `Box<dyn Error>`? That would solve the ergonomics and also still let you mix and match by default.

**Comment by TheButlah** [comment]
I think I misunderstood how this library works. I assumed that there was a way at the toplevel to actually get the values of the errors from the subsystems, instead of simply printing out the errors.

**Comment by Finomnis** [comment]
@TheButlah actually, making the type a default parameter is a great idea, I think. I might use that.

**Comment by Finomnis** [comment]
I'll close this issue. If there is more feedback, let's continue in a new issue.
