### ISSUE TITLE
Restart failed tasks

### ISSUE THREAD

**Issue by dlight** [Finomnis/tokio-graceful-shutdown#5]
Hello! Do you think that this crate could be extended be used to restart failed tasks? That way we could have the same unit of abstraction (a "subsystem", which is a wrapper around a task) for both handling graceful shutdowns and recovering from failure (in case of panic this maybe means wrapping the future on `catch_unwind` before calling `tokio::spawn`, but there could be other ways to signal failure).

The reason I'm asking is that since `tokio-graceful-shutdown` is in charge of spawning the tasks, I can't have another crate (say, an hypothetical `tokio-restart`) fulfill this role. Any code that wanted to do restarts would need to hook on some internals of `tokio-graceful-shutdown`. Moreover, if a task is failed and the policy was not to restart it, then during the graceful shutdown it shouldn't be terminated.

And well, if this is done, then `Toplevel::start` can't receive just a closure anymore; it must receive two (one for the spawned future, another that decides whether the task is restarted if it fails), or maybe define a trait with two methods and receive a trait object there; the default impl for the new method could be to just not restart anything.

**Comment by Finomnis** [comment]
I don't think `std::panic::catch_unwind` works with asynchronous systems.
But there is [future::catch_unwind](https://docs.rs/futures/0.3.17/futures/future/trait.FutureExt.html#method.catch_unwind) from the futures crait.
Actually using the `future::catch_unwind`, it should already be possible.

You kind of brought me onto something here, which might improve my code a lot.
I didn't know that a thing as catch_unwind exists for futures until I googled it, so thanks :)
Let me try to craft an example that fulfills your needs.

**Comment by Finomnis** [comment]
`catch_unwind` seems to not be the solution here.

The problem seems to be that many things are not safe to unwind.
The following things seem to be incompatible with unwinding:
- tokio::sleep
- tokio::Mutex
- tokio::select

There IS, however, a way to catch panics reliably, and that is by listening to `tokio::spawn`'s `JoinHandle`.
It returns a specific error when the subsystem panics.

With this knowledge, I am currently rewriting my entire panic handling system :D

Afterwards, I will add an example that demonstrates a subsystem with auto-restart.
It doesn't actually require any help from this crate and can be implemented completely in the application.

**Comment by Finomnis** [comment]
Once the merge request is in master, this is how you could implement a self-restarting service:

https://github.com/Finomnis/tokio-graceful-shutdown/blob/749b30adfcd5ecbf495cbfeaacf8e42c580edd85/examples/12_subsystem_auto_restart.rs

Is that about what you had in mind?
I don't think there will be an easy way to support this in my API, at least not without breaking changes

**Comment by Finomnis** [comment]
Closed due to no further activity.
